- name: Reset kubeadm
  shell:
    kubeadm reset -f

- name: Install kubeadm
  yum: 
    name: kubectl
    state: latest

- name: Initialization kubernetes cluster
  shell: kubeadm init --apiserver-advertise-address={{ master_addr }} --pod-network-cidr=10.244.0.0/16
  register: output

- name: Storing logs and generated token for future
  local_action: copy content={{ output.stdout }} dest={{ HOME_DIR }}/{{ token }}

- name: Copy required files
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install Flannel
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml
