- name: Install Roles from Galaxy
  hosts: all
  tasks:
    - name: installing required ansible-galaxy roles
      command: "ansible-galaxy install --ignore-errors -r requirements.yaml"
      delegate_to: localhost

- name: Deploy Harbor
  hosts: harbor
  become: yes
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - nicholasamorim.harbor

